// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClearComponentCache
{
    static class Vsix
    {
        public const string Id = "f5028141-9dd0-4ac4-ae6d-0481ae9a940d";
        public const string Name = "Clear MEF Component Cache";
        public const string Description = "Clears the Visual Studio MEF component cache to fix issues with cache corruption.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "mef, component, cache, clean";
    }
}
